/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as HandbookIndexRouteImport } from './routes/handbook.index'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as AuthenticatedStaffIndexRouteImport } from './routes/_authenticated/staff.index'
import { Route as HandbookSectionIdDocumentIdRouteImport } from './routes/handbook.$sectionId.$documentId'
import { Route as AuthenticatedStaffLibraryIdIndexRouteImport } from './routes/_authenticated/staff.$libraryId.index'
import { Route as AuthenticatedStaffLibraryIdSplatRouteImport } from './routes/_authenticated/staff.$libraryId.$'
import { Route as AuthenticatedStaffFaqIndexRouteImport } from './routes/_authenticated/staff.faq.index'
import { Route as AuthenticatedStaffFaqThreadIdRouteImport } from './routes/_authenticated/staff.faq.$threadId'
import { Route as AuthenticatedStaffLibraryIdSectionIdDocumentIdRouteImport } from './routes/_authenticated/staff.$libraryId.$sectionId.$documentId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const HandbookIndexRoute = HandbookIndexRouteImport.update({
  id: '/handbook/',
  path: '/handbook/',
  getParentRoute: () => rootRouteImport,
} as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedStaffIndexRoute = AuthenticatedStaffIndexRouteImport.update({
  id: '/staff/',
  path: '/staff/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const HandbookSectionIdDocumentIdRoute =
  HandbookSectionIdDocumentIdRouteImport.update({
    id: '/handbook/$sectionId/$documentId',
    path: '/handbook/$sectionId/$documentId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedStaffLibraryIdIndexRoute =
  AuthenticatedStaffLibraryIdIndexRouteImport.update({
    id: '/staff/$libraryId/',
    path: '/staff/$libraryId/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStaffLibraryIdSplatRoute =
  AuthenticatedStaffLibraryIdSplatRouteImport.update({
    id: '/staff/$libraryId/$',
    path: '/staff/$libraryId/$',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStaffFaqIndexRoute =
  AuthenticatedStaffFaqIndexRouteImport.update({
    id: '/staff/faq/',
    path: '/staff/faq/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStaffFaqThreadIdRoute =
  AuthenticatedStaffFaqThreadIdRouteImport.update({
    id: '/staff/faq/$threadId',
    path: '/staff/faq/$threadId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStaffLibraryIdSectionIdDocumentIdRoute =
  AuthenticatedStaffLibraryIdSectionIdDocumentIdRouteImport.update({
    id: '/staff/$libraryId/$sectionId/$documentId',
    path: '/staff/$libraryId/$sectionId/$documentId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/reset-password': typeof ResetPasswordRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/handbook/': typeof HandbookIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/handbook/$sectionId/$documentId': typeof HandbookSectionIdDocumentIdRoute
  '/staff/': typeof AuthenticatedStaffIndexRoute
  '/staff/$libraryId/$': typeof AuthenticatedStaffLibraryIdSplatRoute
  '/staff/faq/$threadId': typeof AuthenticatedStaffFaqThreadIdRoute
  '/staff/$libraryId/': typeof AuthenticatedStaffLibraryIdIndexRoute
  '/staff/faq/': typeof AuthenticatedStaffFaqIndexRoute
  '/staff/$libraryId/$sectionId/$documentId': typeof AuthenticatedStaffLibraryIdSectionIdDocumentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/reset-password': typeof ResetPasswordRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/handbook': typeof HandbookIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/handbook/$sectionId/$documentId': typeof HandbookSectionIdDocumentIdRoute
  '/staff': typeof AuthenticatedStaffIndexRoute
  '/staff/$libraryId/$': typeof AuthenticatedStaffLibraryIdSplatRoute
  '/staff/faq/$threadId': typeof AuthenticatedStaffFaqThreadIdRoute
  '/staff/$libraryId': typeof AuthenticatedStaffLibraryIdIndexRoute
  '/staff/faq': typeof AuthenticatedStaffFaqIndexRoute
  '/staff/$libraryId/$sectionId/$documentId': typeof AuthenticatedStaffLibraryIdSectionIdDocumentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/reset-password': typeof ResetPasswordRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/handbook/': typeof HandbookIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/handbook/$sectionId/$documentId': typeof HandbookSectionIdDocumentIdRoute
  '/_authenticated/staff/': typeof AuthenticatedStaffIndexRoute
  '/_authenticated/staff/$libraryId/$': typeof AuthenticatedStaffLibraryIdSplatRoute
  '/_authenticated/staff/faq/$threadId': typeof AuthenticatedStaffFaqThreadIdRoute
  '/_authenticated/staff/$libraryId/': typeof AuthenticatedStaffLibraryIdIndexRoute
  '/_authenticated/staff/faq/': typeof AuthenticatedStaffFaqIndexRoute
  '/_authenticated/staff/$libraryId/$sectionId/$documentId': typeof AuthenticatedStaffLibraryIdSectionIdDocumentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/mcp'
    | '/reset-password'
    | '/.well-known/oauth-protected-resource'
    | '/admin'
    | '/handbook/'
    | '/.lovable/oauth/consent'
    | '/handbook/$sectionId/$documentId'
    | '/staff/'
    | '/staff/$libraryId/$'
    | '/staff/faq/$threadId'
    | '/staff/$libraryId/'
    | '/staff/faq/'
    | '/staff/$libraryId/$sectionId/$documentId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/mcp'
    | '/reset-password'
    | '/.well-known/oauth-protected-resource'
    | '/admin'
    | '/handbook'
    | '/.lovable/oauth/consent'
    | '/handbook/$sectionId/$documentId'
    | '/staff'
    | '/staff/$libraryId/$'
    | '/staff/faq/$threadId'
    | '/staff/$libraryId'
    | '/staff/faq'
    | '/staff/$libraryId/$sectionId/$documentId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/mcp'
    | '/reset-password'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/admin'
    | '/handbook/'
    | '/.lovable/oauth/consent'
    | '/handbook/$sectionId/$documentId'
    | '/_authenticated/staff/'
    | '/_authenticated/staff/$libraryId/$'
    | '/_authenticated/staff/faq/$threadId'
    | '/_authenticated/staff/$libraryId/'
    | '/_authenticated/staff/faq/'
    | '/_authenticated/staff/$libraryId/$sectionId/$documentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  McpRoute: typeof McpRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  HandbookIndexRoute: typeof HandbookIndexRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  HandbookSectionIdDocumentIdRoute: typeof HandbookSectionIdDocumentIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/handbook/': {
      id: '/handbook/'
      path: '/handbook'
      fullPath: '/handbook/'
      preLoaderRoute: typeof HandbookIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/staff/': {
      id: '/_authenticated/staff/'
      path: '/staff'
      fullPath: '/staff/'
      preLoaderRoute: typeof AuthenticatedStaffIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/handbook/$sectionId/$documentId': {
      id: '/handbook/$sectionId/$documentId'
      path: '/handbook/$sectionId/$documentId'
      fullPath: '/handbook/$sectionId/$documentId'
      preLoaderRoute: typeof HandbookSectionIdDocumentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/staff/$libraryId/': {
      id: '/_authenticated/staff/$libraryId/'
      path: '/staff/$libraryId'
      fullPath: '/staff/$libraryId/'
      preLoaderRoute: typeof AuthenticatedStaffLibraryIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/staff/$libraryId/$': {
      id: '/_authenticated/staff/$libraryId/$'
      path: '/staff/$libraryId/$'
      fullPath: '/staff/$libraryId/$'
      preLoaderRoute: typeof AuthenticatedStaffLibraryIdSplatRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/staff/faq/': {
      id: '/_authenticated/staff/faq/'
      path: '/staff/faq'
      fullPath: '/staff/faq/'
      preLoaderRoute: typeof AuthenticatedStaffFaqIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/staff/faq/$threadId': {
      id: '/_authenticated/staff/faq/$threadId'
      path: '/staff/faq/$threadId'
      fullPath: '/staff/faq/$threadId'
      preLoaderRoute: typeof AuthenticatedStaffFaqThreadIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/staff/$libraryId/$sectionId/$documentId': {
      id: '/_authenticated/staff/$libraryId/$sectionId/$documentId'
      path: '/staff/$libraryId/$sectionId/$documentId'
      fullPath: '/staff/$libraryId/$sectionId/$documentId'
      preLoaderRoute: typeof AuthenticatedStaffLibraryIdSectionIdDocumentIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedStaffIndexRoute: typeof AuthenticatedStaffIndexRoute
  AuthenticatedStaffLibraryIdSplatRoute: typeof AuthenticatedStaffLibraryIdSplatRoute
  AuthenticatedStaffFaqThreadIdRoute: typeof AuthenticatedStaffFaqThreadIdRoute
  AuthenticatedStaffLibraryIdIndexRoute: typeof AuthenticatedStaffLibraryIdIndexRoute
  AuthenticatedStaffFaqIndexRoute: typeof AuthenticatedStaffFaqIndexRoute
  AuthenticatedStaffLibraryIdSectionIdDocumentIdRoute: typeof AuthenticatedStaffLibraryIdSectionIdDocumentIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedStaffIndexRoute: AuthenticatedStaffIndexRoute,
  AuthenticatedStaffLibraryIdSplatRoute: AuthenticatedStaffLibraryIdSplatRoute,
  AuthenticatedStaffFaqThreadIdRoute: AuthenticatedStaffFaqThreadIdRoute,
  AuthenticatedStaffLibraryIdIndexRoute: AuthenticatedStaffLibraryIdIndexRoute,
  AuthenticatedStaffFaqIndexRoute: AuthenticatedStaffFaqIndexRoute,
  AuthenticatedStaffLibraryIdSectionIdDocumentIdRoute:
    AuthenticatedStaffLibraryIdSectionIdDocumentIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  McpRoute: McpRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  HandbookIndexRoute: HandbookIndexRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  HandbookSectionIdDocumentIdRoute: HandbookSectionIdDocumentIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
